desc_project{
    type="app-docker"
    projectSite=false
    withDocker=true
    withRegistry=false
    withQuarkus=true
    version{
        majorVersion=11
        mediumVersion=1
        minorVersion=1
    }
    artefact{
        group="fr.lixbox.lixbox-registry"
        project="lixbox-registry"
        projectKey="${group}:${project}"
        dockerImageKey="lixboxteam"
    }
	uri{
	   api_context="/registry/api"
	   api="/registry/api/1.0"
	   ui_context="/registry/ui"
	   ui="/registry/ui" 
	}
	pic{
	    channel="lixbox"
		git{
    	    uri="https://scm.service.dev.lan/${channel}/${desc_project.artefact.project}.git"
    	}    	
        jenkins{
            uri="https://ci.service.dev.lan/view/${channel}/job/${desc_project.artefact.project}-pipeline"
        }   
        sonar{
            uri="https://quality.service.dev.lan/dashboard?id=${desc_project.artefact.group}%3A${desc_project.artefact.project}"
        }
    }
}

artifactoryRepository{
	contextUrl="https://repos.service.dev.lan/artifactory"
    username="lixbox.jenkins.bot"
    password=".TL1b0sc!"
	lixboxRelease	{	
		name="lixbox-release"
	}
    lixboxSnapshot {
        name="lixbox-snapshot"
    }
    libsRelease{
		name="libs-release"
	}
}

sonarRepository{
	host{
		url="https://quality.service.dev.lan"
        username="lixbox.sonar.bot"
        password="@L1xb0x!"
	}
}